package com.exam.ort.enums;

public enum Role {
    ADMIN, USER, MANAGER, ADMIN_READ, ADMIN_WRITE, MANAGER_READ,
    MANAGER_WRITE, ADMIN_CREATE, MANAGER_CREATE, ADMIN_DELETE,
    MANAGER_DELETE, ADMIN_UPDATE, MANAGER_UPDATE
}
